### ISSUE TITLE
Marketify's CSS hijacks all input fields display css setting

### ISSUE THREAD

**Issue by chriscct7** [Astoundify/marketify#448]
From style.css:
https://github.com/Astoundify/marketify/blob/master/style.css#L1592

``` css
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
textarea,
.entry-content .edd_download_quantity_wrapper input {
  line-height: 25px;
  color: #515a63;
  padding: 10px;
  background: #fff;
  border: 1px solid #bdc3c7;
  display: block;
  width: 100%;
  box-shadow: none;
  border-radius: 0;
  -webkit-box-sizing: border-box;
  -moz-box-siding: border-box;
  box-sizing: border-box; }
```

Note the `display: block`. That breaks FES 2.3 and probably a million other plugins that use fields that rely (for example) on hidden fields. Like for example a honeypot field would be a hidden text field, that now gets shown because Marketify is overriding all the things. That definately needs to more targeted.
In the case of FES, it overrode a CSS rule FES added that targeted the class of a specific input field ( `.{specific css class name} input` ), causing https://github.com/chriscct7/edd-fes/issues/742
